"""`brat clone` - turn a real device into a profile.

This is the command the rest of the toolkit is built around. It walks a
device's advertising data and its entire GATT tree, and writes a YAML profile
that `brat impersonate` can stand back up as a working peripheral.

The point is that nobody should have to hand-author a profile. Cloning your own
device produces a file you can immediately serve, diff against a later firmware
version, or commit as a regression fixture.

What it cannot capture is the application-layer protocol - a GATT walk sees the
pipe, not the frames going through it. `brat impersonate` logs those frames so
you can write the `protocol:` block afterwards; a stub is emitted for that
purpose when a transparent serial service is detected.
"""

from __future__ import annotations

import asyncio
from datetime import datetime, timezone
from pathlib import Path

from bleak import BleakClient

from ..core import ble
from ..core.console import Console
from ..core.findings import Finding, Severity
from ..core.profile import (
    AdvertisingSpec,
    CharacteristicSpec,
    DescriptorSpec,
    MatchSpec,
    Profile,
    SecuritySpec,
    ServiceSpec,
)
from ..core.report import Report
from ..core.uuids import label as uuid_label
from ..core.uuids import risk_for, short_form

# Characteristics whose captured contents are per-unit or personal. Cloning
# copies them verbatim, so the operator gets told they are in the file.
_PII_CHARS = {"2a23", "2a25", "2a50", "2a00"}

# See core/ble.py - a stated timeout does not reliably bound a stuck D-Bus
# call, so connect+enumerate gets its own hard wall-clock deadline here too.
_HARD_DEADLINE_MARGIN = 15.0

HEADER_TEMPLATE = """\
# BRAT device profile
#
# Generated by `brat clone` from a live device on {timestamp}.
#   source address : {address}
#   adapter        : {adapter}
#
# This file is data, not code. Every BRAT command is generic; this profile is
# what points one at a specific device.
#
#   brat posture     --profile {slug}   posture-check against these expectations
#   brat impersonate --profile {slug}   serve this GATT tree as a rogue peripheral
#
# BEFORE COMMITTING THIS FILE, review it. A clone copies values verbatim,
# which can include serial numbers, tokens, and other per-unit identifiers.
{warnings}
"""


def _properties_of(char) -> list[str]:
    return sorted(str(p).lower() for p in char.properties)


async def execute(args, console: Console) -> Report:
    report = Report(command="clone", target=args.address)
    verbose = args.output == "text"

    # -- advertising --------------------------------------------------------
    if verbose:
        console.info("Capturing advertising data ...")

    scan_result: ble.ScanResult | None = None
    try:
        seen = await ble.scan(timeout=min(args.timeout, 8.0), adapter=args.adapter)
        scan_result = next(
            (r for r in seen if r.address.lower() == args.address.lower()), None
        )
    except Exception as exc:  # noqa: BLE001
        report.note(f"Advertising scan failed ({exc}).")

    if scan_result is None:
        report.note(
            "Device was not observed advertising. The profile's advertising and match "
            "blocks were built from GATT data alone and may be incomplete."
        )
        if verbose:
            console.warn("No advertisement captured - advertising block will be thin.")
    elif verbose:
        console.ok(
            f"Advertising captured: name={scan_result.name!r}, "
            f"{len(scan_result.service_uuids)} service UUID(s), "
            f"address type {scan_result.address_type.value}"
        )

    # -- GATT ---------------------------------------------------------------
    if verbose:
        console.info(f"Connecting to {args.address} ...")

    try:
        device = await ble.find_device(args.address, timeout=10.0, adapter=args.adapter)
    except Exception:  # noqa: BLE001 - fall back to connecting by address directly
        device = None
    client_kwargs = {"timeout": args.timeout}
    if args.adapter:
        client_kwargs["adapter"] = args.adapter
    client = BleakClient(device or args.address, **client_kwargs)

    read_values = not args.no_values

    async def _connect_and_enumerate():
        await client.connect()
        if verbose:
            console.ok("Connected. Walking GATT tree ...")
        services = await ble.enumerate_gatt(client, read_values=read_values)
        return services, getattr(client, "mtu_size", None)

    try:
        services, mtu = await asyncio.wait_for(
            _connect_and_enumerate(), timeout=args.timeout + _HARD_DEADLINE_MARGIN
        )
    except Exception as exc:  # noqa: BLE001
        result, detail = ble.classify_error(exc)
        report.data = {
            "address": args.address,
            "connected": False,
            "error": detail,
            "error_class": result.value,
        }
        report.note(f"Cloning aborted: could not connect and enumerate ({detail}).")
        return report
    finally:
        try:
            await asyncio.wait_for(client.disconnect(), timeout=5.0)
        except Exception:  # noqa: BLE001
            pass

    # -- build the profile --------------------------------------------------
    slug = args.slug or _derive_slug(scan_result, args.address)
    device_name = args.name or (scan_result.name if scan_result else None) or slug

    profile = Profile(
        slug=slug,
        name=device_name,
        vendor=args.vendor or "",
        source=f"brat clone from {args.address} on "
        f"{datetime.now(timezone.utc).date().isoformat()}",
    )

    # Match block: prefer service UUIDs over the name - names are trivially
    # spoofed and are frequently truncated in advertising packets.
    profile.match = MatchSpec(
        name=scan_result.name if scan_result and scan_result.name else None,
        service_uuids=list(scan_result.service_uuids) if scan_result else [],
    )
    if not profile.match.name and not profile.match.service_uuids:
        profile.match.address = args.address

    profile.advertising = AdvertisingSpec(
        local_name=(scan_result.name if scan_result else device_name),
        service_uuids=list(scan_result.service_uuids) if scan_result else [],
        manufacturer_data=(
            {k: v.hex() for k, v in scan_result.manufacturer_data.items()}
            if scan_result
            else {}
        ),
        appearance=scan_result.appearance if scan_result else None,
    )

    sensitive: list[str] = []
    pii_found: list[str] = []
    captured_values = 0

    for service in services:
        spec = ServiceSpec(
            uuid=service.uuid,
            name=uuid_label(service.uuid, "service"),
            primary=True,
            handle=service.handle,
        )

        for char in service.characteristics:
            cspec = CharacteristicSpec(
                uuid=char.uuid,
                name=uuid_label(char.uuid, "characteristic"),
                properties=list(char.properties),
                handle=char.handle,
                descriptors=[
                    DescriptorSpec(uuid=d["uuid"], name=d["name"])
                    for d in char.descriptors
                ],
            )

            if char.value is not None:
                cspec.value = char.value.hex()
                captured_values += 1
                if short_form(char.uuid) in _PII_CHARS and char.value:
                    pii_found.append(f"{uuid_label(char.uuid, 'characteristic')} ({char.uuid})")

            risk = risk_for(char.uuid)
            if risk:
                cspec.notes = risk.label
                if risk.category in ("sensitive-data", "firmware-update", "proprietary-protocol"):
                    sensitive.append(char.uuid)

            spec.characteristics.append(cspec)

        profile.services.append(spec)

    # Everything was reachable without pairing, so record that as the observed
    # posture. The `expect_*` fields stay at the secure default: they describe
    # what the device *should* do, which is what makes posture findings possible.
    profile.security = SecuritySpec(
        expect_encryption=True,
        expect_pairing=True,
        expect_bonding=False,
        sensitive_characteristics=sorted(set(sensitive)),
        observed={
            "cloned_without_pairing": True,
            "att_mtu": mtu,
            "address_type": scan_result.address_type.value if scan_result else "unknown",
            "values_captured": captured_values,
        },
    )

    # Protocol stub when a transparent serial service is present. It is
    # always emitted as header comments, never as a live `protocol_config` (a
    # clone cannot know the actual frame format from GATT structure alone).
    protocol_hint = _protocol_hint(profile) if not args.no_protocol_stub else ""

    # -- write --------------------------------------------------------------
    out_path = Path(args.output_file) if args.output_file else Path("profiles") / f"{slug}.yaml"

    warnings = ""
    if pii_found:
        warnings = "#\n# NOTE: captured values include per-unit identifiers:\n" + "".join(
            f"#   - {p}\n" for p in pii_found
        )

    header = HEADER_TEMPLATE.format(
        timestamp=datetime.now(timezone.utc).isoformat(timespec="seconds"),
        address=args.address,
        adapter=args.adapter or "default",
        slug=slug,
        warnings=warnings,
    )
    if protocol_hint:
        header += protocol_hint

    profile.save(out_path, header=header)

    problems = profile.validate()

    report.data = {
        "address": args.address,
        "slug": slug,
        "name": device_name,
        "path": str(out_path),
        "service_count": len(profile.services),
        "characteristic_count": sum(len(s.characteristics) for s in profile.services),
        "values_captured": captured_values,
        "sensitive_characteristics": profile.security.sensitive_characteristics,
        "identifiers_captured": pii_found,
        "validation_problems": problems,
        "ready_to_impersonate": not problems,
    }

    if pii_found:
        report.findings.add(
            Finding(
                check="clone.identifiers-captured",
                title="Cloned profile contains per-unit identifiers",
                severity=Severity.INFO,
                target=str(out_path),
                description=(
                    "The clone copied characteristic values verbatim, and some of them "
                    "identify this specific unit. That is what makes the impersonation "
                    "convincing, and it is also why this file should not be committed "
                    "or shared without review."
                ),
                evidence={"characteristics": pii_found},
                remediation="Review the file, or re-run with --no-values for a structure-only clone.",
            )
        )

    if not read_values:
        report.note(
            "Ran with --no-values: characteristic contents were not captured, so an "
            "impersonated device will serve empty values."
        )
    report.note(
        "A GATT walk captures the transport, not the application protocol. If this "
        "device speaks a framed protocol over a serial-bridge characteristic, run "
        "`brat impersonate` and read the logged frames to write a `protocol:` block."
    )

    return report


def _derive_slug(scan_result: ble.ScanResult | None, address: str) -> str:
    if scan_result and scan_result.name:
        cleaned = "".join(
            ch.lower() if ch.isalnum() else "_" for ch in scan_result.name
        ).strip("_")
        cleaned = "_".join(part for part in cleaned.split("_") if part)
        if cleaned:
            return cleaned
    return "device_" + address.replace(":", "").lower()


def _protocol_hint(profile: Profile) -> str:
    """Emit a commented protocol scaffold when a serial bridge is present."""
    serial_chars = [
        c
        for _s, c in profile.all_characteristics()
        if (risk_for(c.uuid) or None) and risk_for(c.uuid).category == "proprietary-protocol"
    ]
    if not serial_chars:
        return ""

    return """#
# ---------------------------------------------------------------------------
# This device exposes a transparent serial bridge, which means it almost
# certainly speaks a framed vendor protocol that a GATT walk cannot see.
#
# To capture it: run `brat impersonate --profile <this file> --confirm`, let the
# real client connect, and read the logged frames. Then add a protocol block:
#
# protocol:
#   name: my-device
#   frame:
#     fields:
#       - {name: start,   type: const, value: "A5"}
#       - {name: cmd,     type: u8}
#       - {name: length,  type: u16be, length_of: payload}
#       - {name: payload, type: bytes, length_from: length}
#       - {name: crc,     type: crc}
#       - {name: end,     type: const, value: "5A"}
#   crc:
#     algorithm: crc16-ibm      # see brat/core/checksum.py for the full list
#     byte_order: big
#   commands:
#     0x01: PING
#   emulation:
#     rules:
#       - on_cmd: 0x01
#         respond:
#           - {cmd: 0x01, payload: "{req.payload[0:4]}01", delay: 0.1}
# ---------------------------------------------------------------------------
"""


def render(report: Report, console: Console) -> None:
    data = report.data

    console.header("CLONED")
    console.kv("source", data["address"])
    console.kv("profile", data["slug"])
    console.kv("written to", data["path"])
    console.kv(
        "captured",
        f"{data['service_count']} services, {data['characteristic_count']} characteristics, "
        f"{data['values_captured']} values",
    )

    if data["sensitive_characteristics"]:
        console.write()
        console.write(f"  {console.bold('Flagged as sensitive:')}")
        for uuid in data["sensitive_characteristics"]:
            console.bullet(f"{uuid_label(uuid, 'characteristic')}  {console.dim(uuid)}", indent=4)

    if data["validation_problems"]:
        console.write()
        console.warn("Profile has issues:")
        for p in data["validation_problems"]:
            console.bullet(p, indent=4)
    else:
        console.write()
        console.ok("Profile is complete and ready to serve.")
        console.write()
        console.write(
            f"    {console.bold('brat impersonate --profile ' + data['path'] + ' --confirm')}"
        )
